MACHINE="imx95-navq"
require conf/machine/imx95-19x19-lpddr5-evk.conf

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
                     freescale/imx95-navqa.dtb \
                     freescale/imx95-navqb.dtb \
                     freescale/imx95-navqa-adacorsa.dtb \
                     freescale/imx95-navqa-argos.dtb \
"

MACHINE_EXTRA_RRECOMMENDS += "kernel-module-uiodma"

KERNEL_MODULE_AUTOLOAD  += "mlan moal btnxpuart rpmsg_tty"
KERNEL_MODULE_PROBECONF += "moal"
module_conf_moal = "options moal fw_name=nxp/sduart_nw61x_v1.bin.se \
cal_data_cfg=none drv_mode=1 cfg80211_wext=0xf drvdbg=0x00000000" 