#@TYPE: Machine
#@NAME: imx95-navq-m7

#@DESCRIPTION: Machine configuration for Cortex-M7 core of NXP i.MX95 SoC.

require conf/machine/include/arm/armv7m/tune-cortexm7.inc

TUNE_FEATURES = "armv7m cortexm7"

ZEPHYR_BOARD = "mr_navq95b/mimx9596/m7"