MACHINE="imx95-navqa"
require conf/machine/imx95-navq.conf

# A0/A1 Silicon
IMX_SOC_REV:${MACHINE} = "A0"
OEI_DDRCONFIG = "XIMX95LPD5EVK19_6400mbps_train_timing_a1"

SYSTEM_MANAGER_CONFIG = "mr-navq95a"
SYSTEM_MANAGER_MONITOR_MODE = "m2"
TARGET_NAME = "imx95-navqa"