# Auto-Generated by cargo-bitbake 0.3.16 (and adapted to add and enable systemd service)
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get rpmsgfs_server could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/rpmsgfs_server/0.1.0"
SRC_URI += "git://git@github.com/NXP-Robotics/rpmsgfs-server.git;protocol=https;nobranch=1;branch=main"
SRCREV = "${AUTOREV}"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+7f79190005"

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += " file://rpmsgfs-server.service"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/bincode/1.3.3 \
    crate://crates.io/bitflags/2.11.0 \
    crate://crates.io/cfg-if/1.0.4 \
    crate://crates.io/cfg_aliases/0.2.1 \
    crate://crates.io/erased-serde/0.4.10 \
    crate://crates.io/itoa/1.0.17 \
    crate://crates.io/libc/0.2.180 \
    crate://crates.io/log/0.4.29 \
    crate://crates.io/nix/0.31.1 \
    crate://crates.io/proc-macro2/1.0.106 \
    crate://crates.io/quote/1.0.44 \
    crate://crates.io/ryu/1.0.23 \
    crate://crates.io/serde/1.0.228 \
    crate://crates.io/serde_core/1.0.228 \
    crate://crates.io/serde_derive/1.0.228 \
    crate://crates.io/serde_fmt/1.1.0 \
    crate://crates.io/std-logger/0.5.8 \
    crate://crates.io/sval/2.17.0 \
    crate://crates.io/sval_buffer/2.17.0 \
    crate://crates.io/sval_dynamic/2.17.0 \
    crate://crates.io/sval_fmt/2.17.0 \
    crate://crates.io/sval_json/2.17.0 \
    crate://crates.io/sval_nested/2.17.0 \
    crate://crates.io/sval_ref/2.17.0 \
    crate://crates.io/sval_serde/2.17.0 \
    crate://crates.io/syn/2.0.116 \
    crate://crates.io/typeid/1.0.3 \
    crate://crates.io/unicode-ident/1.0.24 \
    crate://crates.io/value-bag-serde1/1.12.0 \
    crate://crates.io/value-bag-sval2/1.12.0 \
    crate://crates.io/value-bag/1.12.0 \
    crate://crates.io/zmij/1.0.21 \
"

SRC_URI[bincode-1.3.3.sha256sum] = "b1f45e9417d87227c7a56d22e471c6206462cba514c7590c09aff4cf6d1ddcad"
SRC_URI[bitflags-2.11.0.sha256sum] = "843867be96c8daad0d758b57df9392b6d8d271134fce549de6ce169ff98a92af"
SRC_URI[cfg-if-1.0.4.sha256sum] = "9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801"
SRC_URI[cfg_aliases-0.2.1.sha256sum] = "613afe47fcd5fac7ccf1db93babcb082c5994d996f20b8b159f2ad1658eb5724"
SRC_URI[erased-serde-0.4.10.sha256sum] = "d2add8a07dd6a8d93ff627029c51de145e12686fbc36ecb298ac22e74cf02dec"
SRC_URI[itoa-1.0.17.sha256sum] = "92ecc6618181def0457392ccd0ee51198e065e016d1d527a7ac1b6dc7c1f09d2"
SRC_URI[libc-0.2.180.sha256sum] = "bcc35a38544a891a5f7c865aca548a982ccb3b8650a5b06d0fd33a10283c56fc"
SRC_URI[log-0.4.29.sha256sum] = "5e5032e24019045c762d3c0f28f5b6b8bbf38563a65908389bf7978758920897"
SRC_URI[nix-0.31.1.sha256sum] = "225e7cfe711e0ba79a68baeddb2982723e4235247aefce1482f2f16c27865b66"
SRC_URI[proc-macro2-1.0.106.sha256sum] = "8fd00f0bb2e90d81d1044c2b32617f68fcb9fa3bb7640c23e9c748e53fb30934"
SRC_URI[quote-1.0.44.sha256sum] = "21b2ebcf727b7760c461f091f9f0f539b77b8e87f2fd88131e7f1b433b3cece4"
SRC_URI[ryu-1.0.23.sha256sum] = "9774ba4a74de5f7b1c1451ed6cd5285a32eddb5cccb8cc655a4e50009e06477f"
SRC_URI[serde-1.0.228.sha256sum] = "9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e"
SRC_URI[serde_core-1.0.228.sha256sum] = "41d385c7d4ca58e59fc732af25c3983b67ac852c1a25000afe1175de458b67ad"
SRC_URI[serde_derive-1.0.228.sha256sum] = "d540f220d3187173da220f885ab66608367b6574e925011a9353e4badda91d79"
SRC_URI[serde_fmt-1.1.0.sha256sum] = "6e497af288b3b95d067a23a4f749f2861121ffcb2f6d8379310dcda040c345ed"
SRC_URI[std-logger-0.5.8.sha256sum] = "8caabc44fb553e203ad4786d114a454f057e1cc0094fb63accc9b2b04afe3169"
SRC_URI[sval-2.17.0.sha256sum] = "c1aaf178a50bbdd86043fce9bf0a5867007d9b382db89d1c96ccae4601ff1ff9"
SRC_URI[sval_buffer-2.17.0.sha256sum] = "f89273e48f03807ebf51c4d81c52f28d35ffa18a593edf97e041b52de143df89"
SRC_URI[sval_dynamic-2.17.0.sha256sum] = "0430f4e18e7eba21a49d10d25a8dec3ce0e044af40b162347e99a8e3c3ced864"
SRC_URI[sval_fmt-2.17.0.sha256sum] = "835f51b9d7331b9d7fc48fc716c02306fa88c4a076b1573531910c91a525882d"
SRC_URI[sval_json-2.17.0.sha256sum] = "13cbfe3ef406ee2366e7e8ab3678426362085fa9eaedf28cb878a967159dced3"
SRC_URI[sval_nested-2.17.0.sha256sum] = "8b20358af4af787c34321a86618c3cae12eabdd0e9df22cd9dd2c6834214c518"
SRC_URI[sval_ref-2.17.0.sha256sum] = "fb5e500f8eb2efa84f75e7090f7fc43f621b9f8b6cde571c635b3855f97b332a"
SRC_URI[sval_serde-2.17.0.sha256sum] = "ca2032ae39b11dcc6c18d5fbc50a661ea191cac96484c59ccf49b002261ca2c1"
SRC_URI[syn-2.0.116.sha256sum] = "3df424c70518695237746f84cede799c9c58fcb37450d7b23716568cc8bc69cb"
SRC_URI[typeid-1.0.3.sha256sum] = "bc7d623258602320d5c55d1bc22793b57daff0ec7efc270ea7d55ce1d5f5471c"
SRC_URI[unicode-ident-1.0.24.sha256sum] = "e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75"
SRC_URI[value-bag-serde1-1.12.0.sha256sum] = "16530907bfe2999a1773ca5900a65101e092c70f642f25cc23ca0c43573262c5"
SRC_URI[value-bag-sval2-1.12.0.sha256sum] = "d00ae130edd690eaa877e4f40605d534790d1cf1d651e7685bd6a144521b251f"
SRC_URI[value-bag-1.12.0.sha256sum] = "7ba6f5989077681266825251a52748b8c1d8a4ad098cc37e440103d0ea717fc0"
SRC_URI[zmij-1.0.21.sha256sum] = "b8848ee67ecc8aedbaf3e4122217aff892639231befc6a1b58d29fff4c2cabaa"

LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=7180ec34ffbd49ea5ccd4e6b239ab0a1 \
"

SUMMARY = "A daemon that serves filesystem access through RpMsg"
HOMEPAGE = "https://github.com/NXP-Robotics/rpmsgfs_server.git"
LICENSE = "BSD-3-Clause"

inherit systemd

do_install:append() {
    install -d ${D}${systemd_system_unitdir}
    install -m 0644 ${UNPACKDIR}/rpmsgfs-server.service ${D}${systemd_system_unitdir}
}

SYSTEMD_SERVICE:${PN} = "rpmsgfs-server.service"
SYSTEMD_AUTO_ENABLE:${PN} = "enable"
